version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    reviewers:
      - 'supahuman'
    assignees:
      - 'supahuman'
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'
    groups:
      storybook:
        patterns:
          - '@storybook/*'
          - 'storybook'
      testing:
        patterns:
          - 'jest'
          - '@testing-library/*'
          - '@types/jest'
      build-tools:
        patterns:
          - 'tsup'
          - 'typescript'
          - 'eslint'
          - 'prettier'
      semantic-release:
        patterns:
          - 'semantic-release'
          - '@semantic-release/*'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    commit-message:
      prefix: 'chore(ci)'
